services:
  web:
    build:
      context: .
      dockerfile: setup/web/Dockerfile
    env_file:
      - .env
    image: mltshp/mltshp-web:latest
    volumes:
      - ./web:/srv/mltshp.com/mltshp
      - ./test:/srv/mltshp.com/mltshp/test
      - ./worker/scripts:/srv/mltshp.com/mltshp/scripts
      - ./setup/database:/srv/mltshp.com/mltshp/setup/database
      - ./mounts/logs:/srv/mltshp.com/logs
      - ./mounts/uploaded:/srv/mltshp.com/uploaded
      - ./mounts/tmpuploads/0:/mnt/tmpuploads/0
      - ./mounts/tmpuploads/1:/mnt/tmpuploads/1
      - ./mounts/tmpuploads/2:/mnt/tmpuploads/2
      - ./mounts/tmpuploads/3:/mnt/tmpuploads/3
      - ./mounts/tmpuploads/4:/mnt/tmpuploads/4
      - ./mounts/tmpuploads/5:/mnt/tmpuploads/5
      - ./mounts/tmpuploads/6:/mnt/tmpuploads/6
      - ./mounts/tmpuploads/7:/mnt/tmpuploads/7
      - ./mounts/tmpuploads/8:/mnt/tmpuploads/8
      - ./mounts/tmpuploads/9:/mnt/tmpuploads/9
      - ./setup/web/supervisor/dev.conf:/etc/mltshp/supervisor.conf
    depends_on:
      - mysql
      - fakes3
    links:
      - mysql
      - fakes3
    networks:
      app_net:
        aliases:
          - mltshp-web
  nginx:
    image: mltshp/nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./setup/nginx/dev.conf:/etc/nginx/nginx.conf
      - ./mounts/logs:/srv/mltshp.com/logs
      - ./mounts/uploaded:/srv/mltshp.com/uploaded
      - ./mounts/tmpuploads/0:/mnt/tmpuploads/0
      - ./mounts/tmpuploads/1:/mnt/tmpuploads/1
      - ./mounts/tmpuploads/2:/mnt/tmpuploads/2
      - ./mounts/tmpuploads/3:/mnt/tmpuploads/3
      - ./mounts/tmpuploads/4:/mnt/tmpuploads/4
      - ./mounts/tmpuploads/5:/mnt/tmpuploads/5
      - ./mounts/tmpuploads/6:/mnt/tmpuploads/6
      - ./mounts/tmpuploads/7:/mnt/tmpuploads/7
      - ./mounts/tmpuploads/8:/mnt/tmpuploads/8
      - ./mounts/tmpuploads/9:/mnt/tmpuploads/9
    depends_on:
      - web
    links:
      - web
    networks:
      app_net:
        aliases:
          - mltshp.localhost
  fakes3:
    image: mltshp/fakes3:latest
    entrypoint: fakes3 --root /srv --license dummy --port 4567
    volumes:
      - ./mounts/fakes3:/srv
    networks:
      app_net:
        aliases:
          - mltshp-testing.fakes3
          - mltshp-dev.fakes3
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - ./mounts/mysql:/var/lib/mysql
      - ./setup/mysql/dev.conf:/etc/mysql/conf.d/mltshp.cnf
      - ./setup/database/db-install.sql:/docker-entrypoint-initdb.d/00_db-install.sql
      - ./setup/database/db-fixtures.sql:/docker-entrypoint-initdb.d/01_db-fixtures.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "mltshp"
      MYSQL_USER: "mltshp"
    networks:
      - app_net

networks:
  app_net:
