version: "2"
services:
  mltshp:
    image: mltshp/mltshp-web
    volumes:
      - .:/srv/mltshp.com/mltshp
      - ./setup/dev/nginx.conf:/etc/nginx/nginx.conf
      - ./setup/dev/supervisord.conf:/etc/supervisor/conf.d/mltshp.conf
      - "${MYSQL_UNIX_PORT}:/var/run/mysqld/mysqld.sock"
    ports:
      - "8000:80"
    depends_on:
      - fakes3
    links:
      - fakes3
    networks:
      app_net:
        aliases:
          - mltshp.dev
  fakes3:
    image: fingershock/fakes3
    networks:
      app_net:
        aliases:
          - mltshp-testing.fakes3
          - mltshp-dev.fakes3

networks:
  app_net:
