import os

settings = {
    "cookie_secret": "secretz",
    "auth_secret" : "ne4om9og3maw8orp2ot9quos5ed8aj3lam6up3ja",
    "xsrf_cookies": True,
    "uploaded_files" : "/tmp/mstshp",
    "debug":True,
    "database_user": "root",
    "database_name": "mltshp",
    "database_password" : "",
    "database_host": "localhost",
    "aws_key": "fake_key_123",
    "aws_secret": "fake_secret_123",
    "aws_host": "localhost",
    "aws_port": 4000,
    "aws_bucket": "mltshp_testing",
    "postmark_api_key":"key here",
    "twitter_consumer_key" : "consumer key",
    "twitter_consumer_secret" : "secret key",
    "twitter_access_key" : "secret key",
    "twitter_access_secret" : "secret key",
    "hoptoad_api_key" : "hoptoad_api_key_here",
    "hoptoad_enabled" : False,
    "max_mb_per_month" : 300,
    "api_hits_per_hour" : 150,
    "use_workers": False,
    "recaptcha_private_key": "private key",
    "recaptcha_public_key": "public key",
}

test_settings = {
    "cookie_secret": "secretz",
    "auth_secret" : "ne4om9og3maw8orp2ot9quos5ed8aj3lam6up3ja",
    "xsrf_cookies": True,
    "uploaded_files" : "/tmp/mstshp",
    "debug":True,
    "database_user": "root",
    "database_name": "mltshp_testing",
    "database_password" : "",
    "database_host": "localhost",
    "aws_key": "fake_key_123",
    "aws_secret": "fake_secret_123",
    "aws_host": "localhost",
    "aws_port": 4000,
    "aws_bucket": "mltshp_testing",
    "postmark_api_key":"postmark_api_key_here",
    "twitter_consumer_key" : "twitter_consumer_key_here",
    "twitter_consumer_secret" : "twitter_consumer_secret_key_here",
    "twitter_access_key" : "twitter_access_key_here",
    "twitter_access_secret" : "twitter_access_secret_here",
    "hoptoad_api_key" : "hoptoad_api_key_here",
    "hoptoad_enabled" : False,
    "max_mb_per_month" : 300,
    "api_hits_per_hour" : 150,
    "use_workers": False,
    "debug_workers": True,
    "recaptcha_private_key": "private key",
    "recaptcha_public_key": "public key",
}
