name: Test Pipeline

env:
    build_number: ${{ github.run_id }}

on:
    push:
        branches-ignore:
            - master
jobs:
    build-web:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Pull latest web image
              run: docker pull mltshp/mltshp-web:latest

            - name: Build and push web image
              run: |
                docker build -t mltshp/mltshp-web:build-${{ env.build_number }} .
                docker push mltshp/mltshp-web:build-${{ env.build_number }}

    test:
        needs: [build-web]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Pull and tag web image
              run: |
                docker pull mltshp/mltshp-web:build-${{ env.build_number }}
                docker tag mltshp/mltshp-web:build-${{ env.build_number }} mltshp/mltshp-web:latest

            - name: Start services with Docker Compose
              run: docker compose -f .buildkite/docker-compose.yml up -d

            - name: Wait for services to be ready
              run: sleep 10

            - name: Run tests
              run: docker exec -t buildkite-mltshp-1 ./run-tests.sh

            - name: Run Coveralls report
              env:
                COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
              run: docker exec -t buildkite-mltshp-1 ./coveralls-report.sh

            - name: Stop services and clean up
              run: |
                docker compose -f .buildkite/docker-compose.yml down
                docker container prune -f
