name: Test Pipeline

env:
    build_number: ${{ github.run_id }}

on:
    push:
        branches-ignore:
            - master
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build and start services with Docker Compose
              run: docker compose -f setup/test/docker-compose.yml --project-directory=. up -d --build

            - name: Wait for services to be ready
              run: sleep 10

            - name: Run tests
              run: docker exec -t test-mltshp-1 ./run-tests.sh

            - name: Stop services and clean up
              run: |
                docker compose -f setup/test/docker-compose.yml --project-directory=. down
                docker container prune -f
