name: Test Pipeline

env:
    build_number: ${{ github.run_id }}

on:
    push:
        branches-ignore:
            - master
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build and start services with Docker Compose
              run: docker compose -f release/docker-compose.yml up -d --build

            - name: Wait for services to be ready
              run: sleep 10

            - name: Run tests
              run: docker exec -t release-mltshp-1 ./run-tests.sh

            - name: Run Coveralls report
              env:
                COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
              run: docker exec -t -e COVERALLS_REPO_TOKEN release-mltshp-1 ./coveralls-report.sh

            - name: Stop services and clean up
              run: |
                docker compose -f release/docker-compose.yml down
                docker container prune -f
